name: Etsy Promotion Code Test

on:
  workflow_dispatch:  # Allow manual trigger

jobs:
  test-promotion-codes:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install Chrome
      run: |
        wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
        sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install undetected-chromedriver==2.1.1
    
    - name: Run promotion code test
      run: python git_sele.py
    
    - name: Upload results
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: results.json
