name: Run Selenium On GitHub Action
on:
  workflow_dispatch:
jobs:
  scrape:
    runs-on: windows-latest
    steps:
      - name: Checking out repo
        uses: actions/checkout@v3
      - name: Setting up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Checking Current folder
        run: pwd
      - name: Doenload chromium browser
        run: curl -L -o chrome-win64.zip https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/117.0.5938.92/win64/chrome-win64.zip
      - name: Checking file downloaded
        run: ls
      - name: unzip chrome
        run: Expand-Archive -LiteralPath 'D:\a\Git_selenium\Git_selenium\chrome-win64.zip' -DestinationPath D:\a\Git_selenium\Git_selenium
      - name: Checking extracted file
        run: cd D:\a\Git_selenium\Git_selenium\chrome-win64 
      - name: Checking file downloaded
        run: ls
