name: Run Selenium On GitHub Action
on:
  workflow_dispatch:
jobs:
  scrape:
    runs-on: windows-latest
    steps:
      - name: Checking out repo
        uses: actions/checkout@v3
      - name: Set screen resolution
        run: |
          powershell -ExecutionPolicy Bypass -File set_resolution.ps1
        shell: powershell
      - name: Setting up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@v4
        with:
          path: "requirements.txt"
      - name: Doenload chromium browser
        run: curl -L -o chrome-win64.zip https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/117.0.5938.92/win64/chrome-win64.zip
      - name: unzip chrome
        run: Expand-Archive -Force D:\a\Git_selenium\Git_selenium\chrome-win64.zip D:\a\Git_selenium\Git_selenium

      - name: Running the Python script
        run: python git_sele_proxy.py
